# Entity Configuration: Accounts
#
# This defines entity-specific settings that override flow defaults.
# Configuration precedence: Entity > Flow > Coordinator

name: accounts

# Entity-specific source configuration
home:
  path: accounts              # Relative to flow base path
  # Final path: data/source/accounts/*.parquet

# Entity-specific destination configuration
store:
  table: dbo.Accounts         # Table name in SQL Server

# Entity-specific options
options:
  batch_size: 100000          # Larger batches for accounts (overrides flow default)
  # Inherits if_exists: replace from flow defaults
