# Entity Configuration: Contacts
#
# This defines entity-specific settings that override flow defaults.
# Configuration precedence: Entity > Flow > Coordinator

name: contacts

# Entity-specific source configuration
home:
  path: contacts              # Relative to flow base path
  # Final path: data/source/contacts/*.parquet

# Entity-specific destination configuration
store:
  table: dbo.Contacts         # Table name in SQL Server

# Entity-specific options
options:
  batch_size: 75000          # Medium batches for contacts (overrides flow default)
  # Inherits if_exists: replace from flow defaults
