# Entity Configuration: Opportunities
#
# This defines entity-specific settings that override flow defaults.
# Configuration precedence: Entity > Flow > Coordinator

name: opportunities

# Entity-specific source configuration
home:
  path: opportunities         # Relative to flow base path
  # Final path: data/source/opportunities/*.parquet

# Entity-specific destination configuration
store:
  table: dbo.Opportunities   # Table name in SQL Server

# Entity-specific options
options:
  batch_size: 25000          # Smaller batches for opportunities (overrides flow default)
  # Inherits if_exists: replace from flow defaults
