# Advanced configuration using full home/store terminology
# This shows the complete hygge API with explicit home and store configuration

flows:
  # Example 1: Basic home/store configuration
  users_flow:
    home:
      type: parquet
      path: data/users.parquet
      options:
        batch_size: 10000
    store:
      type: parquet
      path: data/lake/users
      options:
        batch_size: 100000
        compression: snappy
        file_pattern: "users_{sequence:020d}.parquet"

  # Example 2: High-performance configuration
  large_dataset:
    home:
      type: parquet
      path: data/large_dataset.parquet
      options:
        batch_size: 25000  # Larger batches for reading
    store:
      type: parquet
      path: data/lake/large_dataset
      options:
        batch_size: 200000  # Very large batches for writing
        compression: zstd   # Best compression
        file_pattern: "large_dataset_{sequence:020d}.parquet"
    options:
      queue_size: 15       # Larger queue for high throughput

  # Example 3: Balanced configuration
  orders_flow:
    home:
      type: parquet
      path: data/orders.parquet
      options:
        batch_size: 15000
    store:
      type: parquet
      path: data/lake/orders
      options:
        batch_size: 75000
        compression: gzip   # Good balance of speed/compression
        file_pattern: "orders_{sequence:020d}.parquet"
    options:
      queue_size: 8
