# Entity Pattern for Landing Zones
#
# Use this pattern when you have multiple entities in a landing zone,
# each needing to flow to its own destination.
#
# EXPECTED STRUCTURE:
# Entity directories containing parquet files
#
# landing_zone/
#   ├── users/              → data_lake/users/
#   │   ├── batch_001.parquet
#   │   └── batch_002.parquet
#   ├── orders/             → data_lake/orders/
#   │   ├── batch_001.parquet
#   │   └── batch_002.parquet
#   └── products/           → data_lake/products/
#       └── data.parquet
#
# hygge expects each entity to have its own directory containing one or
# more parquet files. This is the standard pattern for landing zones where
# data arrives in batches or partitions.

flows:
  # Entity pattern - one flow definition, multiple entities
  landing_to_lake:
    home: landing_zone/
    store: data_lake/
    entities:
      - users
      - orders
      - products
    # Behind the scenes, hygge creates one Flow per entity:
    # - landing_zone/users/ → data_lake/users/
    # - landing_zone/orders/ → data_lake/orders/
    # - landing_zone/products/ → data_lake/products/
    # All flows run in parallel via Coordinator

  # Entity pattern with custom options
  landing_to_archive:
    home:
      path: landing_zone/
      options:
        batch_size: 5000
    store:
      path: archive/
      options:
        batch_size: 50000
        compression: gzip
    entities:
      - users
      - orders
    options:
      queue_size: 8

  # You can mix entity patterns with regular flows
  standalone_flow:
    home: special_data/standalone.parquet
    store: output/standalone
