# Simple MSSQL Store with Auto-Create Tables
#
# This example shows how hygge can automatically create tables
# from your data schema when they don't exist.

flows:
  users_to_mssql:
    home:
      type: parquet
      path: data/users.parquet

    store:
      type: mssql
      server: localhost
      database: MyDatabase
      table: dbo.Users
      if_exists: append  # Create if missing, append to existing

      # Optional performance settings
      batch_size: 102400
      parallel_workers: 8
      table_hints: TABLOCK  # For exclusive access during load

# How it works:
# 1. hygge reads data from data/users.parquet
# 2. On first write, checks if dbo.Users exists
# 3. If not, creates table with schema from DataFrame:
#    - String columns → NVARCHAR(4000)
#    - Int64 columns → BIGINT
#    - Float64 columns → FLOAT
#    - Boolean columns → BIT
#    - Datetime columns → DATETIME2
#    - All columns nullable, with Clustered Columnstore Index
# 4. Writes data using high-performance parallel batches

# if_exists options:
# - "fail" (default): Error if table exists
# - "append": Use existing table, create if missing
# - "replace": Drop existing table and recreate
